version: '3'

services:
  spring:
    build: ./backend
    container_name: spring
    networks:
      - tingle-network
    depends_on:
      - mysql
    ports:
      - 8080:8080
    environment:
      - TZ=Asia/Seoul
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/tingle
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=ssafy
  mysql:
    image: mysql:8.0.26
    container_name: mysql
    restart: always
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=root
      - MYSQL_ROOT_PASSWORD=ssafy
    ports:
      - 3306:3306
    networks:
      - tingle-network
    volumes: 
      - ./mysql/init/:/docker-entrypoint-initdb.d/

networks:
  tingle-network: