version: '3'

services:
  mysql:
    # build: ./db
    image: mysql:8.0.26
    container_name: mysql
    restart: always
    environment:
      - TZ=Asia/Seoul
      - MYSQL_DATABASE=tingle
      - MYSQL_ROOT_PASSWORD=ssafy
    ports:
      - 3306:3306
    networks:
      - match-network
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
    volumes: 
      # - ./mysql/conf.d:/etc/mysql/conf.d
      # - ./mysql/data:/var/lib/mysql
      - ./db/:/docker-entrypoint-initdb.d/
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
      - '2181:2181'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
    networks:
      - match-network
  kafka:
    image: 'bitnami/kafka:latest'
    ports:
      - '9092:9092'
    environment:
      - KAFKA_BROKER_ID=1
      - KAFKA_CFG_LISTENERS=PLAINTEXT://:9092
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://127.0.0.1:9092
      # - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes
    depends_on:
      - zookeeper
    networks:
      - match-network
  redis:
    image: "redis"
    container_name: redis
    ports:
      - "6379:6379"


networks:
  match-network:

# volumes:
#   mysql: {}
  # redis: {}
